INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (1, 'AD', 'Andorra');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (2, 'AE', 'Emiratos Árabes Unidos');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (3, 'AF', 'Afganistán');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (4, 'AG', 'Antigua y Barbuda');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (5, 'AI', 'Anguilla');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (6, 'AL', 'Albania');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (7, 'AM', 'Armenia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (8, 'AN', 'Antillas Holandesas');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (9, 'AO', 'Angola');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (10, 'AQ', 'Antártida');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (11, 'AR', 'Argentina');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (12, 'AS', 'Samoa Americana');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (13, 'AT', 'Austria');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (14, 'AU', 'Australia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (15, 'AW', 'Aruba');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (16, 'AX', 'Islas Gland');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (17, 'AZ', 'Azerbaiyán');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (18, 'BA', 'Bosnia y Herzegovina');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (19, 'BB', 'Barbados');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (20, 'BD', 'Bangladesh');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (21, 'BE', 'Bélgica');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (22, 'BF', 'Burkina Faso');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (23, 'BG', 'Bulgaria');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (24, 'BH', 'Bahréin');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (25, 'BI', 'Burundi');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (26, 'BJ', 'Benin');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (27, 'BM', 'Bermudas');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (28, 'BN', 'Brunéi');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (29, 'BO', 'Bolivia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (30, 'BR', 'Brasil');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (31, 'BS', 'Bahamas');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (32, 'BT', 'Bhután');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (33, 'BV', 'Isla Bouvet');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (34, 'BW', 'Botsuana');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (35, 'BY', 'Bielorrusia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (36, 'BZ', 'Belice');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (37, 'CA', 'Canadá');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (38, 'CC', 'Islas Cocos');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (39, 'CD', 'República Democrática del Congo');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (40, 'CF', 'República Centroafricana');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (41, 'CG', 'Congo');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (42, 'CH', 'Suiza');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (43, 'CI', 'Costa de Marfil');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (44, 'CK', 'Islas Cook');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (45, 'CL', 'Chile');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (46, 'CM', 'Camerún');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (47, 'CN', 'China');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (48, 'CO', 'Colombia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (49, 'CR', 'Costa Rica');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (50, 'CS', 'Serbia y Montenegro');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (51, 'CU', 'Cuba');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (52, 'CV', 'Cabo Verde');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (53, 'CX', 'Isla de Navidad');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (54, 'CY', 'Chipre');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (55, 'CZ', 'República Checa');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (56, 'DE', 'Alemania');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (57, 'DJ', 'Yibuti');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (58, 'DK', 'Dinamarca');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (59, 'DM', 'Dominica');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (60, 'DO', 'República Dominicana');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (61, 'DZ', 'Argelia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (62, 'EC', 'Ecuador');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (63, 'EE', 'Estonia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (64, 'EG', 'Egipto');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (65, 'EH', 'Sahara Occidental');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (66, 'ER', 'Eritrea');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (67, 'ES', 'España');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (68, 'ET', 'Etiopía');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (69, 'FI', 'Finlandia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (70, 'FJ', 'Fiyi');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (71, 'FK', 'Islas Malvinas');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (72, 'FM', 'Micronesia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (73, 'FO', 'Islas Feroe');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (74, 'FR', 'Francia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (75, 'GA', 'Gabón');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (76, 'GB', 'Reino Unido');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (77, 'GD', 'Granada');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (78, 'GE', 'Georgia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (79, 'GF', 'Guayana Francesa');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (80, 'GH', 'Ghana');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (81, 'GI', 'Gibraltar');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (82, 'GL', 'Groenlandia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (83, 'GM', 'Gambia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (84, 'GN', 'Guinea');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (85, 'GP', 'Guadalupe');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (86, 'GQ', 'Guinea Ecuatorial');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (87, 'GR', 'Grecia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (88, 'GS', 'Islas Georgias del Sur y Sandwich del Sur');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (89, 'GT', 'Guatemala');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (90, 'GU', 'Guam');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (91, 'GW', 'Guinea-Bissau');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (92, 'GY', 'Guyana');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (93, 'HK', 'Hong Kong');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (94, 'HM', 'Islas Heard y McDonald');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (95, 'HN', 'Honduras');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (96, 'HR', 'Croacia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (97, 'HT', 'Haití');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (98, 'HU', 'Hungría');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (99, 'ID', 'Indonesia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (100, 'IE', 'Irlanda');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (101, 'IL', 'Israel');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (102, 'IN', 'India');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (103, 'IO', 'Territorio Británico del Océano Índico');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (104, 'IQ', 'Iraq');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (105, 'IR', 'Irán');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (106, 'IS', 'Islandia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (107, 'IT', 'Italia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (108, 'JM', 'Jamaica');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (109, 'JO', 'Jordania');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (110, 'JP', 'Japón');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (111, 'KE', 'Kenia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (112, 'KG', 'Kirguistán');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (113, 'KH', 'Camboya');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (114, 'KI', 'Kiribati');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (115, 'KM', 'Comoras');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (116, 'KN', 'San Cristóbal y Nevis');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (117, 'KP', 'Corea del Norte');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (118, 'KR', 'Corea del Sur');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (119, 'KW', 'Kuwait');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (120, 'KY', 'Islas Caimán');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (121, 'KZ', 'Kazajstán');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (122, 'LA', 'Laos');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (123, 'LB', 'Líbano');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (124, 'LC', 'Santa Lucía');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (125, 'LI', 'Liechtenstein');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (126, 'LK', 'Sri Lanka');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (127, 'LR', 'Liberia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (128, 'LS', 'Lesotho');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (129, 'LT', 'Lituania');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (130, 'LU', 'Luxemburgo');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (131, 'LV', 'Letonia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (132, 'LY', 'Libia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (133, 'MA', 'Marruecos');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (134, 'MC', 'Mónaco');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (135, 'MD', 'Moldavia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (136, 'MG', 'Madagascar');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (137, 'MH', 'Islas Marshall');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (138, 'MK', 'ARY Macedonia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (139, 'ML', 'Malí');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (140, 'MM', 'Myanmar');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (141, 'MN', 'Mongolia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (142, 'MO', 'Macao');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (143, 'MP', 'Islas Marianas del Norte');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (144, 'MQ', 'Martinica');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (145, 'MR', 'Mauritania');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (146, 'MS', 'Montserrat');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (147, 'MT', 'Malta');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (148, 'MU', 'Mauricio');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (149, 'MV', 'Maldivas');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (150, 'MW', 'Malawi');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (151, 'MX', 'México');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (152, 'MY', 'Malasia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (153, 'MZ', 'Mozambique');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (154, 'NA', 'Namibia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (155, 'NC', 'Nueva Caledonia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (156, 'NE', 'Níger');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (157, 'NF', 'Isla Norfolk');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (158, 'NG', 'Nigeria');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (159, 'NI', 'Nicaragua');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (160, 'NL', 'Países Bajos');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (161, 'NO', 'Noruega');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (162, 'NP', 'Nepal');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (163, 'NR', 'Nauru');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (164, 'NU', 'Niue');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (165, 'NZ', 'Nueva Zelanda');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (166, 'OM', 'Omán');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (167, 'PA', 'Panamá');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (168, 'PE', 'Perú');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (169, 'PF', 'Polinesia Francesa');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (170, 'PG', 'Papúa Nueva Guinea');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (171, 'PH', 'Filipinas');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (172, 'PK', 'Pakistán');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (173, 'PL', 'Polonia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (174, 'PM', 'San Pedro y Miquelón');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (175, 'PN', 'Islas Pitcairn');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (176, 'PR', 'Puerto Rico');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (177, 'PS', 'Palestina');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (178, 'PT', 'Portugal');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (179, 'PW', 'Palau');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (180, 'PY', 'Paraguay');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (181, 'QA', 'Qatar');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (182, 'RE', 'Reunión');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (183, 'RO', 'Rumania');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (184, 'RU', 'Rusia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (185, 'RW', 'Ruanda');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (186, 'SA', 'Arabia Saudí');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (187, 'SB', 'Islas Salomón');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (188, 'SC', 'Seychelles');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (189, 'SD', 'Sudán');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (190, 'SE', 'Suecia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (191, 'SG', 'Singapur');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (192, 'SH', 'Santa Helena');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (193, 'SI', 'Eslovenia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (194, 'SJ', 'Svalbard y Jan Mayen');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (195, 'SK', 'Eslovaquia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (196, 'SL', 'Sierra Leona');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (197, 'SM', 'San Marino');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (198, 'SN', 'Senegal');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (199, 'SO', 'Somalia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (200, 'SR', 'Surinam');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (201, 'ST', 'Santo Tomé y Príncipe');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (202, 'SV', 'El Salvador');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (203, 'SY', 'Siria');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (204, 'SZ', 'Suiza');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (205, 'TC', 'Islas Turcas y Caicos');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (206, 'TD', 'Chad');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (207, 'TF', 'Territorios Australes Franceses');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (208, 'TG', 'Togo');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (209, 'TH', 'Tailandia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (210, 'TJ', 'Tayikistán');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (211, 'TK', 'Tokelau');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (212, 'TL', 'Timor Oriental');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (213, 'TM', 'Turkmenistán');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (214, 'TN', 'Túnez');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (215, 'TO', 'Tonga');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (216, 'TR', 'Turquía');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (217, 'TT', 'Trinidad y Tobago');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (218, 'TV', 'Tuvalu');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (219, 'TW', 'Taiwán');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (220, 'TZ', 'Tanzania');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (221, 'UA', 'Ucrania');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (222, 'UG', 'Uganda');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (223, 'UM', 'Islas ultramarinas de Estados Unidos');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (224, 'US', 'Estados Unidos');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (225, 'UY', 'Uruguay');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (226, 'UZ', 'Uzbekistán');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (227, 'VA', 'Ciudad del Vaticano');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (228, 'VC', 'San Vicente y las Granadinas');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (229, 'VE', 'Venezuela');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (230, 'VG', 'Islas Vírgenes Británicas');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (231, 'VI', 'Islas Vírgenes de los Estados Unidos');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (232, 'VN', 'Vietnam');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (233, 'VU', 'Vanuatu');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (234, 'WF', 'Wallis y Futuna');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (235, 'WS', 'Samoa');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (236, 'YE', 'Yemen');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (237, 'YT', 'Mayotte');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (238, 'ZA', 'Sudáfrica');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (239, 'ZM', 'Zambia');
INSERT INTO `country` (`id`, `iso`, `name`)  VALUES (240, 'ZW', 'Zimbabue');