INSERT INTO `province` (`id`, `name`, `id`)  VALUES (1, 'Álava', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (2, 'Albacete', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (3, 'Alicante', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (4, 'Almería', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (5, 'Ávila', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (6, 'Badajoz', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (7, 'Baleares (Illes)', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (8, 'Barcelona', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (9, 'Burgos', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (10, 'Cáceres', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (11, 'Cádiz', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (12, 'Castellón', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (13, 'Ciudad Real', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (14, 'Córdoba', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (15, 'A Coruña', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (16, 'Cuenca', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (17, 'Girona', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (18, 'Granada', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (19, 'Guadalajara', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (20, 'Guipúzcoa', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (21, 'Huelva', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (22, 'Huesca', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (23, 'Jaén', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (24, 'León', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (25, 'Lleida', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (26, 'La Rioja', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (27, 'Lugo', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (28, 'Madrid', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (29, 'Málaga', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (30, 'Murcia', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (31, 'Navarra', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (32, 'Ourense', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (33, 'Asturias', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (34, 'Palencia', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (35, 'Las Palmas', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (36, 'Pontevedra', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (37, 'Salamanca', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (38, 'Santa Cruz de Tenerife', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (39, 'Cantabria', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (40, 'Segovia', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (41, 'Sevilla', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (42, 'Soria', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (43, 'Tarragona', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (44, 'Teruel', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (45, 'Toledo', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (46, 'Valencia', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (47, 'Valladolid', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (48, 'Vizcaya', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (49, 'Zamora', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (50, 'Zaragoza', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (51, 'Ceuta', 67);
INSERT INTO `province` (`id`, `name`, `id`)  VALUES (52, 'Melilla', 67);